"""add_discovered_source_document_type

Revision ID: 4548830e47ce
Revises: 21
Create Date: 2025-09-09 15:48:30.561622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4548830e47ce'
down_revision: Union[str, None] = '21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_sources_created_at'), table_name='notebook_sources')
    op.drop_index(op.f('ix_notebook_sources_search_space_id'), table_name='notebook_sources')
    op.drop_index(op.f('ix_notebook_sources_source_ref_id'), table_name='notebook_sources')
    op.drop_table('notebook_sources')
    op.drop_index(op.f('ix_source_refs_canonical_id'), table_name='source_refs')
    op.drop_index(op.f('ix_source_refs_created_at'), table_name='source_refs')
    op.drop_index(op.f('ix_source_refs_hash'), table_name='source_refs')
    op.drop_index(op.f('ix_source_refs_kind'), table_name='source_refs')
    op.drop_index(op.f('ix_source_refs_provider'), table_name='source_refs')
    op.drop_table('source_refs')
    op.drop_index(op.f('chucks_search_index'), table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('chucks_vector_index'), table_name='chunks', postgresql_using='hnsw')
    op.drop_index(op.f('document_search_index'), table_name='documents', postgresql_using='gin')
    op.drop_index(op.f('document_vector_index'), table_name='documents', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('document_vector_index'), 'documents', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('document_search_index'), 'documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('chucks_vector_index'), 'chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('chucks_search_index'), 'chunks', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_table('source_refs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('canonical_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ttl_sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("mode::text = ANY (ARRAY['live'::character varying, 'snapshot'::character varying]::text[])", name='ck_source_refs_mode'),
    sa.PrimaryKeyConstraint('id', name='source_refs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_source_refs_provider'), 'source_refs', ['provider'], unique=False)
    op.create_index(op.f('ix_source_refs_kind'), 'source_refs', ['kind'], unique=False)
    op.create_index(op.f('ix_source_refs_hash'), 'source_refs', ['hash'], unique=False)
    op.create_index(op.f('ix_source_refs_created_at'), 'source_refs', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_refs_canonical_id'), 'source_refs', ['canonical_id'], unique=False)
    op.create_table('notebook_sources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('search_space_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_ref_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], name=op.f('fk_notebook_sources_added_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], name=op.f('fk_notebook_sources_search_space_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ref_id'], ['source_refs.id'], name=op.f('fk_notebook_sources_source_ref_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notebook_sources_pkey')),
    sa.UniqueConstraint('search_space_id', 'source_ref_id', name=op.f('uq_notebook_sources_search_space_source'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notebook_sources_source_ref_id'), 'notebook_sources', ['source_ref_id'], unique=False)
    op.create_index(op.f('ix_notebook_sources_search_space_id'), 'notebook_sources', ['search_space_id'], unique=False)
    op.create_index(op.f('ix_notebook_sources_created_at'), 'notebook_sources', ['created_at'], unique=False)
    # ### end Alembic commands ###
