"""add_discovery_chat_type

Revision ID: bb542acf8975
Revises: a3f6b27dc3a0
Create Date: 2025-09-09 19:33:17.452041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb542acf8975'
down_revision: Union[str, None] = 'a3f6b27dc3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chucks_search_index'), table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('chucks_vector_index'), table_name='chunks', postgresql_using='hnsw')
    op.drop_index(op.f('document_search_index'), table_name='documents', postgresql_using='gin')
    op.drop_index(op.f('document_vector_index'), table_name='documents', postgresql_using='hnsw')
    
    # Add DISCOVERY to ChatType enum
    op.execute("ALTER TYPE chattype ADD VALUE 'DISCOVERY';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('document_vector_index'), 'documents', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('document_search_index'), 'documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('chucks_vector_index'), 'chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index(op.f('chucks_search_index'), 'chunks', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
